### ISSUE TITLE
hand and object Masks 

### ISSUE THREAD

**Issue by anilesec** [facebookresearch/ContactPose#12]
Dear @samarth-robo ,

Is it possible to download the hand and object masks readily? I mean without running rendering scripts for all the sequences. 
Is it possible to recover the mask from the depth maps provided?

Thank you!

**Comment by samarth-robo** [comment]
hi @anilesec,

The masks are not available for direct download, unfortunately. You will need to run the hand and object rendering step at least once.

If the [pyrender setup instructions](https://github.com/facebookresearch/ContactPose/blob/main/docs/rendering.md) did not work for you, can you please add the error messages here so that we can publicly document the fix?

Also, we are not limited to pyrender. If you are more comfortable with another renderer, I am happy to help interface ContactPose with that and add the instructions to GitHub.

**Comment by anilesec** [comment]
Thanks, @samarth-robo I made it work finally. It was due to a mismatch in GPU compute architectures.

**Comment by samarth-robo** [comment]
@anilesec glad to hear that. If possible, please post the steps you took here, so that others who face the same issue have a solution.
